.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel snd989_entry
    /* 3A240 0003A1A0 0000C041 */ .word 0x41C00000 /* invalid instruction */
    /* 3A244 0003A1A4 00000000 */ .word 0x0
    /* 3A248 0003A1A8 08010000 */ .word 0x00000108 /* invalid instruction */
    /* 3A24C 0003A1AC 736E6439 */ .word 0x39646E73
    /* 3A250 0003A1B0 38390000 */ .word 0x00003938
    /* 3A254 0003A1B4 B0F00000 */ .word InitResidentModule
    /* 3A258 0003A1B8 B8A30300 */ .word _retonly
    /* 3A25C 0003A1BC B8A30300 */ .word _retonly
    /* 3A260 0003A1C0 B8A30300 */ .word _retonly
    /* 3A264 0003A1C4 08F80000 */ .word snd_StartSoundSystemEx /* invalid instruction */
    /* 3A268 0003A1C8 A8FD0000 */ .word snd_StopSoundSystem /* invalid instruction */
    /* 3A26C 0003A1CC C8F70000 */ .word snd_SystemRunning /* invalid instruction */
    /* 3A270 0003A1D0 64FB0000 */ .word snd_InstallSoundTick /* invalid instruction */
    /* 3A274 0003A1D4 00FD0000 */ .word snd_RemoveSoundTick
    /* 3A278 0003A1D8 CC0E0100 */ .word snd_BankLoadEx /* invalid instruction */
    /* 3A27C 0003A1DC A0220100 */ .word snd_BankLoadByLocEx /* invalid instruction */
    /* 3A280 0003A1E0 CC250100 */ .word snd_UnloadBank /* invalid instruction */
    /* 3A284 0003A1E4 CC290100 */ .word snd_MMDLoad /* invalid instruction */
    /* 3A288 0003A1E8 442D0100 */ .word snd_MMDLoadByLoc /* invalid instruction */
    /* 3A28C 0003A1EC C02D0100 */ .word snd_UnloadMMD
    /* 3A290 0003A1F0 BC3F0100 */ .word snd_ResolveBankXREFS
    /* 3A294 0003A1F4 44780300 */ .word snd_SetMasterVolume /* invalid instruction */
    /* 3A298 0003A1F8 347A0300 */ .word snd_GetMasterVolume
    /* 3A29C 0003A1FC 887A0300 */ .word snd_SetPlaybackMode /* invalid instruction */
    /* 3A2A0 0003A200 B87A0300 */ .word snd_GetPlaybackMode
    /* 3A2A4 0003A204 4C370300 */ .word snd_SetMixerMode /* invalid instruction */
    /* 3A2A8 0003A208 24CD0100 */ .word snd_SetReverbType /* invalid instruction */
    /* 3A2AC 0003A20C B8D30100 */ .word snd_SetReverbDepth
    /* 3A2B0 0003A210 207C0000 */ .word snd_AutoReverb /* invalid instruction */
    /* 3A2B4 0003A214 00A90100 */ .word snd_PlaySoundVolPanPMPB
    /* 3A2B8 0003A218 00AC0100 */ .word snd_SoundIsStillPlaying
    /* 3A2BC 0003A21C A0AC0100 */ .word snd_IsSoundALooper /* invalid instruction */
    /* 3A2C0 0003A220 8CBA0100 */ .word snd_PauseSound /* invalid instruction */
    /* 3A2C4 0003A224 78BB0100 */ .word snd_ContinueSound
    /* 3A2C8 0003A228 88AB0100 */ .word snd_StopSound /* invalid instruction */
    /* 3A2CC 0003A22C 64BC0100 */ .word snd_StopAllSoundsInBank /* invalid instruction */
    /* 3A2D0 0003A230 74F10100 */ .word snd_StopAllSounds
    /* 3A2D4 0003A234 5CAE0100 */ .word snd_SetSoundVolPan /* invalid instruction */
    /* 3A2D8 0003A238 B4B40100 */ .word snd_SetSoundPitch
    /* 3A2DC 0003A23C 38B10100 */ .word snd_GetSoundOriginalPitch
    /* 3A2E0 0003A240 D8B20100 */ .word snd_GetSoundCurrentPitch /* invalid instruction */
    /* 3A2E4 0003A244 64B50100 */ .word snd_SetSoundPitchBend /* invalid instruction */
    /* 3A2E8 0003A248 B4B30100 */ .word snd_GetSoundPitchBend
    /* 3A2EC 0003A24C 1CB60100 */ .word snd_SetSoundPitchModifier /* invalid instruction */
    /* 3A2F0 0003A250 6CB90100 */ .word snd_GetSoundPitchModifier /* invalid instruction */
    /* 3A2F4 0003A254 38870000 */ .word snd_AutoVol
    /* 3A2F8 0003A258 F0680000 */ .word snd_AutoPan
    /* 3A2FC 0003A25C C8760000 */ .word snd_AutoPitch /* invalid instruction */
    /* 3A300 0003A260 78710000 */ .word snd_AutoPitchBend
    /* 3A304 0003A264 48F20000 */ .word snd_SetMIDIRegister_E /* invalid instruction */
    /* 3A308 0003A268 98F20000 */ .word snd_GetMIDIRegister_E /* invalid instruction */
    /* 3A30C 0003A26C F0F20000 */ .word snd_SetGlobalExcite_E
    /* 3A310 0003A270 28F30000 */ .word snd_GetGlobalExcite_E /* invalid instruction */
    /* 3A314 0003A274 64220200 */ .word snd_InitVAGStreamingEx /* invalid instruction */
    /* 3A318 0003A278 78350200 */ .word snd_PlayVAGStreamByLocEx
    /* 3A31C 0003A27C 7C540200 */ .word snd_PauseVAGStream
    /* 3A320 0003A280 1C580200 */ .word snd_PauseAllStreams /* invalid instruction */
    /* 3A324 0003A284 04590200 */ .word snd_ContinueVAGStream /* invalid instruction */
    /* 3A328 0003A288 18460200 */ .word snd_GetVAGStreamQueueCount /* invalid instruction */
    /* 3A32C 0003A28C 60210300 */ .word snd_SetVAGStreamVolPan /* invalid instruction */
    /* 3A330 0003A290 58600200 */ .word snd_StopVAGStream /* invalid instruction */
    /* 3A334 0003A294 8C140300 */ .word snd_CloseVAGStreaming /* invalid instruction */
    /* 3A338 0003A298 B0500200 */ .word snd_StopAllStreams
    /* 3A33C 0003A29C C8810200 */ .word snd_GetVAGStreamLoc /* invalid instruction */
    /* 3A340 0003A2A0 B4830200 */ .word snd_GetVAGStreamTimeRemaining
    /* 3A344 0003A2A4 A4840200 */ .word snd_GetVAGStreamTotalTime /* invalid instruction */
    /* 3A348 0003A2A8 74150300 */ .word snd_StreamSafeCheckCDIdle
    /* 3A34C 0003A2AC F88A0200 */ .word snd_StreamSafeCdRead
    /* 3A350 0003A2B0 9C8F0200 */ .word snd_StreamSafeCdReadEEm /* invalid instruction */
    /* 3A354 0003A2B4 CC920200 */ .word snd_StreamSafeCdSync /* invalid instruction */
    /* 3A358 0003A2B8 208D0200 */ .word snd_StreamSafeCdBreak /* invalid instruction */
    /* 3A35C 0003A2BC 5C940200 */ .word snd_StreamSafeCdGetError /* invalid instruction */
    /* 3A360 0003A2C0 50EE0100 */ .word snd_PauseAllSoundsInGroup /* invalid instruction */
    /* 3A364 0003A2C4 50F00100 */ .word snd_ContinueAllSoundsInGroup /* invalid instruction */
    /* 3A368 0003A2C8 B8590300 */ .word snd_GetVoiceStatus
    /* 3A36C 0003A2CC FC210200 */ .word snd_GetTick
    /* 3A370 0003A2D0 6C390300 */ .word snd_LockVoiceAllocatorEx /* invalid instruction */
    /* 3A374 0003A2D4 343B0300 */ .word snd_ExternVoiceAlloc
    /* 3A378 0003A2D8 9C3C0300 */ .word snd_ExternVoiceFree /* invalid instruction */
    /* 3A37C 0003A2DC EC3A0300 */ .word snd_UnlockVoiceAllocator /* invalid instruction */
    /* 3A380 0003A2E0 70F30000 */ .word snd_SRAMMalloc_E
    /* 3A384 0003A2E4 F0F30000 */ .word snd_SRAMMarkUsed_E
    /* 3A388 0003A2E8 78F40000 */ .word snd_SRAMFree_E
    /* 3A38C 0003A2EC D8F60000 */ .word snd_SRAMGetFreeMem_E /* invalid instruction */
    /* 3A390 0003A2F0 50F70000 */ .word snd_SRAMMaxFreeBlockSize_E /* invalid instruction */
    /* 3A394 0003A2F4 E8F40000 */ .word snd_GetDopplerPitchMod_E /* invalid instruction */
    /* 3A398 0003A2F8 64F50000 */ .word snd_MIDINoteOn_E /* invalid instruction */
    /* 3A39C 0003A2FC 9CF50000 */ .word snd_MIDINoteOff_E /* invalid instruction */
    /* 3A3A0 0003A300 D4F50000 */ .word snd_PitchBend_E /* invalid instruction */
    /* 3A3A4 0003A304 0CF60000 */ .word snd_MIDITo360Pan_E
    /* 3A3A8 0003A308 68F60000 */ .word snd_ReleaseDamper_E /* invalid instruction */
    /* 3A3AC 0003A30C A0F60000 */ .word snd_ResetControllers_E /* invalid instruction */
    /* 3A3B0 0003A310 BC970000 */ .word snd_PlaySFXGrain
    /* 3A3B4 0003A314 60530100 */ .word snd_GetFreeSPUDMA /* invalid instruction */
    /* 3A3B8 0003A318 78540100 */ .word snd_FreeSPUDMA
    /* 3A3BC 0003A31C 34750300 */ .word snd_KeyOnVoiceRaw
    /* 3A3C0 0003A320 84760300 */ .word snd_KeyOffVoiceRaw /* invalid instruction */
    /* 3A3C4 0003A324 A8A00100 */ .word snd_SetPanTable /* invalid instruction */
    /* 3A3C8 0003A328 00000000 */ .word snd_RegisterExternProcHandler
    /* 3A3CC 0003A32C 20010000 */ .word snd_UnregisterExternProcHandler /* invalid instruction */
    /* 3A3D0 0003A330 60020000 */ .word snd_FindExternProcHandler /* invalid instruction */
    /* 3A3D4 0003A334 C0380300 */ .word snd_SetGroupVoiceRange
    /* 3A3D8 0003A338 50030100 */ .word snd_RegisterIOPMemAllocator /* invalid instruction */
    /* 3A3DC 0003A33C 1C1D0100 */ .word snd_FileRead /* invalid instruction */
    /* 3A3E0 0003A340 24860200 */ .word snd_IsVAGStreamBuffered /* invalid instruction */
    /* 3A3E4 0003A344 F43C0000 */ .word snd_RegisterErrorDisplayFunc
    /* 3A3E8 0003A348 6CCC0100 */ .word snd_SetReverbEx /* invalid instruction */
    /* 3A3EC 0003A34C 80C90100 */ .word snd_PreAllocReverbWorkArea
    /* 3A3F0 0003A350 84090100 */ .word snd_GetLastLoadError /* invalid instruction */
    /* 3A3F4 0003A354 54180200 */ .word snd_SRAMDumpFreeBlocks /* invalid instruction */
    /* 3A3F8 0003A358 08A40100 */ .word snd_PlaySoundByNameVolPanPMPB /* invalid instruction */
    /* 3A3FC 0003A35C 70A10100 */ .word snd_GetSoundUserData
    /* 3A400 0003A360 2C3E0000 */ .word snd_Install989Monitor /* invalid instruction */
    /* 3A404 0003A364 7C190200 */ .word snd_GetFreeBlockSize
    /* 3A408 0003A368 D0EE0000 */ .word snd_ResetAllHandlersForSound /* invalid instruction */
    /* 3A40C 0003A36C CC0F0100 */ .word snd_IterateBlockListToMonitor /* invalid instruction */
    /* 3A410 0003A370 94230100 */ .word snd_BankLoadFromEEEx /* invalid instruction */
    /* 3A414 0003A374 24960100 */ .word snd_SetMovieSoundVolPan /* invalid instruction */
    /* 3A418 0003A378 04250100 */ .word snd_BankLoadFromIOPEx /* invalid instruction */
    /* 3A41C 0003A37C C0A50100 */ .word snd_PlaySoundEx
    /* 3A420 0003A380 30B70100 */ .word snd_GetSoundReg
    /* 3A424 0003A384 FCB70100 */ .word snd_SetSoundReg
    /* 3A428 0003A388 C0B80100 */ .word snd_SetAllSoundReg
    /* 3A42C 0003A38C 80240100 */ .word snd_GetSRAMUsedByBank
    /* 3A430 0003A390 1C9E0300 */ .word snd_SetMasterVolumeDucker /* invalid instruction */
    /* 3A434 0003A394 D4330200 */ .word snd_PlayVAGStreamByNameEx /* invalid instruction */
    /* 3A438 0003A398 04300200 */ .word snd_SetVAGStreamChannelRange
    /* 3A43C 0003A39C D41D0300 */ .word snd_SetVAGStreamSubGroupVolPan /* invalid instruction */
    /* 3A440 0003A3A0 E8C80100 */ .word snd_SetReverbMode /* invalid instruction */
    /* 3A444 0003A3A4 989A0000 */ .word snd_GetSFXGlobalReg /* invalid instruction */
    /* 3A448 0003A3A8 209B0000 */ .word snd_SetSFXGlobalReg /* invalid instruction */
    /* 3A44C 0003A3AC 74AF0100 */ .word snd_SetSoundParams
    /* 3A450 0003A3B0 AC8D0200 */ .word snd_StreamSafeCdSearchFile /* invalid instruction */
    /* 3A454 0003A3B4 00000000 */ .word 0x0
.size snd989_entry, . - snd989_entry

glabel _retonly
    /* 3A458 0003A3B8 0800E003 */  jr         $ra
    /* 3A45C 0003A3BC 00000000 */   nop
.size _retonly, . - _retonly
