name: 989snd debug
sha1: 74663d1f02c1ff7118744a66b064bcd307b2262b
options:
    # paths
    basename: 989SND_D.IRX
    target_path: in/989SND_D.IRX
    base_path: ..
    
    asm_path: asm
    src_path: src
    build_path: build

    extensions_path: tools/splat_ext 
    symbol_addrs_path: config/symbol_addrs.txt
    undefined_funcs_auto_path: config/undefined_funcs_auto.txt
    undefined_syms_auto_path:  config/undefined_syms_auto.txt

    named_regs_for_c_funcs: False
    
    # compiler 
    compiler: GCC
    platform: psx

    string_encoding: ASCII
    
    section_order: [".iopmod", ".text", ".rel.text", ".rodata", ".rel.rodata", ".data", ".rel.data", ".sbss", ".bss"]

segments:
    - [0, databin, elf_header]
    - [0x74, databin, iopmod]
    - name: text
      type: code
      start: 0xa0
      vram: 0x0
      bss_size: 0x9df0
      subsegments:
        # .text
        - [0xa0, c, 989snd]
        - [0x3efc, asm, LFO]
        - [0x4e68, asm, ame]
        - [0x6990, asm, autopan]
        - [0x7218, asm, autopb]
        - [0x7768, asm, autoptch]
        - [0x7cc0, asm, autoverb]
        - [0x87d8, asm, autovol]
        - [0x8ec4, asm, blocksnd]
        - [0xf150, asm, extern]
        - [0xf868, asm, init]
        - [0x10014, asm, intr_code]
        - [0x102cc, asm, loader]
        - [0x1560c, asm, midi]
        - [0x17fe0, asm, moviesnd]
        - [0x19d20, asm, my_rand]
        - [0x1a148, asm, pantable]
        - [0x1a210, asm, playsnd]
        - [0x1c988, asm, reverb]
        - [0x1d818, asm, sndhand]
        - [0x20148, asm, sram]
        - [0x21b3c, asm, stick]
        - [0x22304, asm, stream]
        - [0x335b4, asm, valloc]
        - [0x37800, asm, vol]
        - [0x3a240, asm, export_stub]
        - [0x3a460, asm, import_stub]
         # .rodata
        - [0x3a80c, rodata]
        # .data
        - [0x3b018, data]
        # .sbss / .bss
        - { start: 0x3cf94, type: sbss, vram: 0x3cef4 }
        - { start: 0x3cf94, type: bss, vram: 0x3cf34 }
        
    - [0x3cf94, databin] # .mdebug
    - [0x134c30, databin] # .shstrtab
    - [0x134ecc, databin] # .rel.text
    - [0x145da4, databin] # .rel.rodata
    - [0x145f1c, databin] # .rel.data
    - [0x146424, databin] # .symtab
    - [0x149d64, databin] # .strtab
